#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TMP_DIR="$ROOT_DIR/.tmp/e2e"
RECORDS_DIR="$TMP_DIR/records"
DATA_DIR="$TMP_DIR/data"
TEXTBOOK_SOURCE_DIR="$TMP_DIR/textbook-source"
TEXTBOOK_WORK_DIR="$TMP_DIR/textbook-work"

rm -rf "$TMP_DIR"
mkdir -p "$RECORDS_DIR" "$DATA_DIR" "$TEXTBOOK_SOURCE_DIR" "$TEXTBOOK_WORK_DIR"

export PORT="${PORT:-3310}"
export E2E_TEST_MODE=1
export RECORDS_PATH="$RECORDS_DIR"
export DB_PATH="$DATA_DIR/e2e.sqlite"
export RECORDS_TIMEZONE="${RECORDS_TIMEZONE:-Asia/Tokyo}"
export TEXTBOOK_FEATURE_ENABLED=1
export KG_ENABLED=0
export KG_PLANNING_ENABLED=0
export KG_LLM_ENRICHMENT_ENABLED=0
export CARD_ANNOTATIONS_ENABLED=1
export CARD_ANNOTATIONS_SHADOW_READ_ENABLED=1
export CARD_ANNOTATIONS_COMPAT_WRITE_ENABLED=1
export TEXTBOOK_SOURCE_ROOT="$TEXTBOOK_SOURCE_DIR"
export TEXTBOOK_WORK_PATH="$TEXTBOOK_WORK_DIR"
export TTS_EN_ENDPOINT=""
export TTS_JA_ENDPOINT=""
export GENERATION_JOB_TRANSIENT_RETRY_BASE_MS="${GENERATION_JOB_TRANSIENT_RETRY_BASE_MS:-200}"
export GENERATION_JOB_TRANSIENT_RETRY_MAX_MS="${GENERATION_JOB_TRANSIENT_RETRY_MAX_MS:-500}"

cd "$ROOT_DIR"
npm run build:react >/dev/null
export NODE_ENV=production
exec node server.mjs
